### ISSUE TITLE
Endpoint to retrieve all FT tokens

### ISSUE THREAD

**Issue by He1DAr** [hirosystems/token-metadata-api#161] opened 2023-06-05 19:32 UTC
Hello team,
We're working on a new page in Explorer that will display a comprehensive list of FTs. Our goal is to create functionality similar to what can be found on https://etherscan.io/tokens.
These are the key features that we would like to include:
1. Token information: the response should return FT token information, including name, symbol, metadata, price, %change, 24h trading volume, circulating market cap, and the number of holders.
2. Search functionality: search for specific tokens by name, symbol, or address.
3. Pagination
Please let me know if more details/clarifications are needed. Thank you!

related to https://github.com/hirosystems/explorer/issues/1088

**Comment by rafaelcr** [comment] 2023-06-10 03:40
Hi @He1DAr sure, we can make this endpoint. However, the following data points are not feasible for this API: 
> price, %change, 24h trading volume, circulating market cap, and the number of holders

The Metadata API does not track any data around holders, market prices, volume, etc. For that, we'd need to either start consuming oracle market data in this API or you'll need to pull this data from an external service like ALEX, Arkadiko, etc. (I *strongly* suggest the latter!)

**Comment by rafaelcr** [comment] 2023-06-10 03:40
Btw I think this may be a duplicate of #154

**Closed** 2023-06-21 16:24 UTC
Labels: feature request
