### ISSUE TITLE
support FTs with variable token supply

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/token-metadata-api#196] opened 2024-02-20 17:16 UTC
Tokens like [SP3K8BC0PPEVCV7NZ6QSRWPQ2JE9E5B6N3PA0KBR9.token-wleo](https://explorer.hiro.so/txid/0x75c72be372030c469a82b81cb9a07a277f3c43f656d4647ff4aa3eb4013e630e?chain=mainnet) wrap other tokens on Stacks, so they don't have a set total supply. Because of this, these contracts return something unexpected when calling `get-total-supply` (an error or something like that) which makes the API ignore them.

```clarity
(define-read-only (get-total-supply)
  ;; least authority Issue D
  ERR-NOT-SUPPORTED
)
```

We should figure out a way to handle these variable token supplies and support a way to include them on the API

**Comment by cuevasm** [comment] 2024-02-21 00:52
Just adding a +1 to this being a good one to prioritize asap 🙏🧡

**Comment by smcclellan** [comment] 2024-06-12 20:45
Marking as duplicate of #146.

**Closed by smcclellan** 2024-06-12 20:45 UTC
Labels: feature request, metadata
